### ISSUE TITLE
Download file from baidu

### ISSUE THREAD

**Issue by huyhoang17** [hikopensource/DAVAR-Lab-OCR#11]
Hi, thanks for the great repo!

I want to try the [LGPMA-table recognition model](https://github.com/hikopensource/DAVAR-Lab-OCR/tree/main/demo/table_recognition/lgpma) but can not download the model weight from Baidu. Can you upload the pre-trained model on google drive?

Thanks in advance!

**Comment by qiaoliang6** [comment]
It has already been uploaded on google drive, and you may find the link in the readme.

**Comment by huyhoang17** [comment]
ah thank you!

**Comment by huyhoang17** [comment]
@qiaoliang6 
Can you also upload the train data in json format to google drive? From this page: https://github.com/hikopensource/DAVAR-Lab-OCR/tree/main/demo/table_recognition/lgpma#preparing-dataset

Thank you!

**Comment by qiaoliang6** [comment]
> @qiaoliang6
> Can you also upload the train data in json format to google drive? From this page: https://github.com/hikopensource/DAVAR-Lab-OCR/tree/main/demo/table_recognition/lgpma#preparing-dataset
> 
> Thank you!

The datalist has been uploaded in the google drive link.

**Comment by huyhoang17** [comment]
Thank you!
