### ISSUE TITLE
LGPMA Training Error：simple_test() got an unexpected keyword argument 'gt_bboxes'

### ISSUE THREAD

**Issue by Letdreamfly** [hikopensource/DAVAR-Lab-OCR#115]
TypeError: simple_test() got an unexpected keyword argument 'gt_bboxes'
请问，LGPMA不支持训练过程的评估吗？还是评测集的标签需要转化成某种格式？

**Comment by qiaoliang6** [comment]
最新的更新中（443b3e6a3a9216af1150e87dc11330912cb81abd）增加了在线评测支持
