### ISSUE TITLE
请问下VSR大概什么时候可以开源呢

### ISSUE THREAD

**Issue by sonack** [hikopensource/DAVAR-Lab-OCR#13]
VSR: A Unified Framework for Document Layout Analysis combining Vision, Semantics and Relations 这篇文章，工作很棒，非常期待！

**Comment by chengzhanzhan** [comment]
预计十月中下旬。

**Comment by sonack** [comment]
> 预计十月中下旬。

好的 期待

**Comment by sonack** [comment]
> 很抱歉，由于目前存在其他紧急任务，VSR的开源工作会一定程度延期，大概率在11月上旬的时候推出。非常感谢您的关注！

请问有具体的时间节点吗？非常期待

**Comment by sonack** [comment]
@chengzhanzhan @qiaoliang6 今天15号了，请问VSR大概还要多久可以开源呢

**Comment by sonack** [comment]
> 很抱歉，由于目前存在其他紧急任务，VSR的开源工作会一定程度延期，大概率在11月上旬的时候推出。非常感谢您的关注！

@qiaoliang6 你好，可以透露下vsr的工作如何了嘛？大概什么时候可以加入到代码库中呢，🥺

**Comment by qiaoliang6** [comment]
> > 很抱歉，由于目前存在其他紧急任务，VSR的开源工作会一定程度延期，大概率在11月上旬的时候推出。非常感谢您的关注！
> 
> @qiaoliang6 你好，可以透露下vsr的工作如何了嘛？大概什么时候可以加入到代码库中呢，🥺

因为在公司里面，相关同事有其他主线任务，导致这部分开源工作排不开，目前已经准备开始代码整理，不出意外的话发布可能在11月底到12月中旬期间吧，非常抱歉！

**Comment by sonack** [comment]
好的，目前领域内只有VSR是3种模态都用上且打算开源的版面分析工作，这么好的工作非常期待能学习一下~

**Comment by ttbuffey** [comment]
请问VSR什么时候开源呢？期待啊

DAVAR-Lab-OCR/demo/text_ie/trie/ 这个支持英文的建立的PII information extraction 吗？
其中ORC agent是用的什么呢？

**Comment by sonack** [comment]
@qiaoliang6 请问现在进度如何了

**Comment by sonack** [comment]
@qiaoliang6 @chengzhanzhan 可以问下现在是什么进展了吗 12月中旬能不能整理完啊

**Comment by sonack** [comment]
@qiaoliang6 @chengzhanzhan It is 12.15 today, the release date of VSR has been put off from mid-to-late of October to this mid of December,  about 2 months delayed.  I will close this issue now.
