### ISSUE TITLE
Plan for sharing ComFinTab dataset, CTUNet

### ISSUE THREAD

**Issue by yellowjs0304** [hikopensource/DAVAR-Lab-OCR#132]
Hi, @qiaoliang6  :) I read your paper, "End-to-End Compound Table Understanding with Multi-Modal Modeling".
I really interested with your benchmark dataset, and model.
I saw that you will gonna release the model or dataset soon.
Do you have any decided plan for sharing the code & dataset?

**Comment by qiaoliang6** [comment]
I'm sorry, all the resources were already in place, but the company has recently tightened censorship of open-source data and code, so it may still take a while.

**Comment by yellowjs0304** [comment]
Got it. If you have a detailed plan for this in later, please comment.
