### ISSUE TITLE
code error

### ISSUE THREAD

**Issue by yang-chenyu104** [hikopensource/DAVAR-Lab-OCR#17]
在/davarocr/tools/文件下直接运行train.py会出现ImportError: cannot import name 'build' from 'mmdet.models.builder' （/home/yangchengyu/anaconda3/envs/pytorch16/lib/python3.8/site-packages/mmdet/models/builder.py)这个问题是mmdet版本不合适引起的吗

**Comment by yang-chenyu104** [comment]
谢谢，正在解决这方面问题!!!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hikopensource/DAVAR-Lab-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月8日(星期五) 晚上7:38
***@***.***&gt;;
抄送:&nbsp;"な法--言说 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hikopensource/DAVAR-Lab-OCR] code error (#17)





 
你可以看一下系统环境中安装的mmdet和mmcv版本是哪个版本的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yang-chenyu104** [comment]
mmdet是2.11.0，mmcv-full是1.3.4,pytorch版本是1.6，python版本是3.8，直接在tool文件夹运行train.py出现
 UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead.
  warnings.warn(
Traceback (most recent call last):
  File "train.py", line 43, in <module>
    from davarocr.davar_ner.models.builder import build_ner
ModuleNotFoundError: No module named 'davarocr.davar_ner'
这样的问题，是要升级mmcv版本吗?

**Comment by qiaoliang6** [comment]
> 谢谢回复，那我可以直接运行tools/train.py文件可以吧，bash文件里面设置和linux服务器设置不一样，会引起其他问问题，就行直接去运行train.py
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hikopensource/DAVAR-Lab-OCR" ***@***.***&gt;; 发送时间:&nbsp;2021年10月8日(星期五) 晚上11:33 ***@***.***&gt;; 抄送:&nbsp;"な法--言说 ***@***.******@***.***&gt;; 主题:&nbsp;Re: [hikopensource/DAVAR-Lab-OCR] code error (#17) mmdet是2.11.0，mmcv-full是1.3.4,pytorch版本是1.6，python版本是3.8，直接在tool文件夹运行train.py出现 UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead. warnings.warn( Traceback (most recent call last): File "train.py", line 43, in from davarocr.davar_ner.models.builder import build_ner ModuleNotFoundError: No module named 'davarocr.davar_ner' 这样的问题，是要升级mmcv版本吗? 抱歉，这个问题属于之前更新时的疏忽，NER相关包还未完成整理上传，因此暂时先移除掉相关引用。代码已经更新。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

可以参考bash的用法直接使用脚本执行也可以

**Comment by yang-chenyu104** [comment]
谢谢解答，对我帮助很大，共勉！！！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "hikopensource/DAVAR-Lab-OCR"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年10月9日(星期六) 晚上7:35
***@***.***&gt;;
抄送:&nbsp;"な法--言说 ***@***.******@***.***&gt;;
主题:&nbsp;Re: [hikopensource/DAVAR-Lab-OCR] code error (#17)





  
谢谢回复，那我可以直接运行tools/train.py文件可以吧，bash文件里面设置和linux服务器设置不一样，会引起其他问问题，就行直接去运行train.py
 …
 ------------------&nbsp;原始邮件&nbsp;------------------ 发件人: "hikopensource/DAVAR-Lab-OCR" @.&gt;; 发送时间:&nbsp;2021年10月8日(星期五) 晚上11:33 @.&gt;; 抄送:&nbsp;"な法--言说 @.@.&gt;; 主题:&nbsp;Re: [hikopensource/DAVAR-Lab-OCR] code error (#17) mmdet是2.11.0，mmcv-full是1.3.4,pytorch版本是1.6，python版本是3.8，直接在tool文件夹运行train.py出现 UserWarning: The old API of register_module(module, force=False) is deprecated and will be removed, please use the new API register_module(name=None, force=False, module=None) instead. warnings.warn( Traceback (most recent call last): File "train.py", line 43, in from davarocr.davar_ner.models.builder import build_ner ModuleNotFoundError: No module named 'davarocr.davar_ner' 这样的问题，是要升级mmcv版本吗? 抱歉，这个问题属于之前更新时的疏忽，NER相关包还未完成整理上传，因此暂时先移除掉相关引用。代码已经更新。 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.
  
可以参考bash的用法直接使用脚本执行也可以
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by yang-chenyu104** [comment]
FileNotFoundError: img file does not exist: /home/yangchengyu/code/DAVAR-Lab-OCR/train/train/Images/train/PMC4159848_008_00.png运行代码出现这个图片找不到我用的"PubTabNet_datalist_train_all.json"这个json文件查了一下发现这个文件在这个json里面，又把json里面得图片从Putabnet图片文件筛选，还是报错这个文件找不到
