### ISSUE TITLE
Training and testing instruction

### ISSUE THREAD

**Issue by iazdan** [hikopensource/DAVAR-Lab-OCR#18]
Will you be able to provide the instruction for training and testing without using ocr (only table / cell detection). It's been really hard to get the code to work using setup.sh. 

Thanks.

**Comment by qiaoliang6** [comment]
You can simply command the code such as "from .davar_det import *" in "/DAVAR-Lab-OCR/davarocr/davarocr/init.py" to select whether to use such package.
