### ISSUE TITLE
Please, why the result of my test based on given models is not so ideal(especially on IC15 datasets)?May I need to change the value of IoU or something else?

### ISSUE THREAD

**Issue by Mark-Laohu** [hikopensource/DAVAR-Lab-OCR#21]

**Comment by Mark-Laohu** [comment]
你好，我用res101_ete_finetune_ic13-2178f7d6.pth和mango_r101_ete_finetune.py测试IC13数据集，lexicon_type = 'STRONG'时得到spot_recall:  0.8972 spot_precision:  0.9612 spot_hmean:  0.9281

**Comment by qiaoliang6** [comment]
> 你好，我用res101_ete_finetune_ic13-2178f7d6.pth和mango_r101_ete_finetune.py测试IC13数据集，lexicon_type = 'STRONG'时得到spot_recall: 0.8972 spot_precision: 0.9612 spot_hmean: 0.9281

这个是因为在不同的数据集上测试的参数会有微小的差异，特别是输入分辨率上，你这组结果应该是用默认给出的分辨率测出的结果。我已经把readme中所有对应的数据集的详细配置都单独给出了，可以完全与readme中汇报的结果一致。

**Comment by Mark-Laohu** [comment]
好的，谢谢解惑！
