### ISSUE TITLE
LGPMA

### ISSUE THREAD

**Issue by Floyd809** [hikopensource/DAVAR-Lab-OCR#22]
![11](https://user-images.githubusercontent.com/83442112/139218670-d84023b4-ff75-44f1-99b6-4a476ab9d38f.png)
![sendpix1](https://user-images.githubusercontent.com/83442112/139218903-73bcef0b-fa95-427e-8513-fdef4f5f9b5f.jpg)
请问测试图片的表格结构输出不太对，这是什么原因？谢谢

**Comment by qiaoliang6** [comment]
文章能够被引用是我们的荣幸。
FileNotFoundError: file "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main-1/demo/table_recognition/lgpma/config/lgpma_pub.py" does not exist
提示中很明显还是路径配置相关错误。

另外，此工程是基于mmdetection框架进行的，一些常见的问题在mmdetection的官方仓库内都有过相似的解答。建议如果对于代码框架不熟悉的，可以先在mmdetection框架下跑通Mask-RCNN模型。LGPMA模型基本上是基于该模型进行的二次开发。

**Comment by Floyd809** [comment]
> 文章能够被引用是我们的荣幸。 FileNotFoundError: file "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main-1/demo/table_recognition/lgpma/config/lgpma_pub.py" does not exist 提示中很明显还是路径配置相关错误。
> 
> 另外，此工程是基于mmdetection框架进行的，一些常见的问题在mmdetection的官方仓库内都有过相似的解答。建议如果对于代码框架不熟悉的，可以先在mmdetection框架下跑通Mask-RCNN模型。LGPMA模型基本上是基于该模型进行的二次开发。

报错确实是这个原因。非常感谢您的解答和建议！！会认真学习该模型。

**Comment by Floyd809** [comment]
> 文章能够被引用是我们的荣幸。 FileNotFoundError: file "/home/ihavc01/Downloads/LG/DAVAR-Lab-OCR-main-1/demo/table_recognition/lgpma/config/lgpma_pub.py" does not exist 提示中很明显还是路径配置相关错误。
> 
> 另外，此工程是基于mmdetection框架进行的，一些常见的问题在mmdetection的官方仓库内都有过相似的解答。建议如果对于代码框架不熟悉的，可以先在mmdetection框架下跑通Mask-RCNN模型。LGPMA模型基本上是基于该模型进行的二次开发。

报错确实是这个原因。非常感谢您的解答和建议！！会认真学习该模型。
