### ISSUE TITLE
'Weak' supervision results (Table 5 in the paper)

### ISSUE THREAD

**Issue by yairkit** [hikopensource/DAVAR-Lab-OCR#24]
Thank you for your work.

1. Are the result of 'Weak' supervision in table 5 evaluated using axis-aligned evaluation protocol?
(i.e. predictions VS ground-truth axis-aligned-boxes) 

2. Can you provide those results for TotalText 'End-To-End'? 
(As I assume the reported results in this table is for Word-Spotting)

Thanks!

**Comment by qiaoliang6** [comment]
Do you talk about the results of MANGO?

1. Yes, In table 5, 'Weak' is means using the aixs-aligned evaluation protocol.
2.  The result of 'End-to-End' has been shown in the [Readme](https://github.com/hikopensource/DAVAR-Lab-OCR/blob/main/demo/text_spotting/mango/readme.md).

**Comment by yairkit** [comment]
Thanks!
regarding 2 - I meant the 'End-to-End' results of the 'Weak' model from table 5

**Comment by qiaoliang6** [comment]
> Thanks! regarding 2 - I meant the 'End-to-End' results of the 'Weak' model from table 5

We didn't test it, you may evaluate it using the released model.
