### ISSUE TITLE
关于MANGO结果的问题

### ISSUE THREAD

**Issue by Gyann-z** [hikopensource/DAVAR-Lab-OCR#25]
您好，为什么我用您提供的模型测试的结果与您表中的不一样呢？
比如ICDAR2015 ResNet-50 General，您给的结果是70.8，我用您给的test_ic15.sh跑出来是69.4。有什么需要注意的吗？
谢谢

**Comment by qiaoliang6** [comment]
看一下issue #21 ，有可能是测试输入分辨率不太一致

**Comment by Gyann-z** [comment]
谢谢您的答复。我重新检查了一遍，我在test_ic15.py里调用的就是您给的config文件：mango_r50_ete_finetune_ic15.py，分辨率是(1800, 1600)，与您github的一样，但结果不一样。而且我尝试把分辨率改成其他数，测试的结果却没有变化，都是69.4。请问您知道是什么原因么？谢谢。

**Comment by cylzty110** [comment]
你可以采用论文中grid_num=60的配置用于测试icdar2015数据集
