### ISSUE TITLE
LGPMA   推理过程  并没有 使用 global_seg_results ， 似乎没找到mask re-score部分的代码

### ISSUE THREAD

**Issue by rcx986635** [hikopensource/DAVAR-Lab-OCR#27]
with_global_seg为True,但是在推理过程 lgpma 的 post_processor 里并没有找到哪里使用了MASK类的预测结果

**Comment by qiaoliang6** [comment]
公开出来的版本在后处理的时候确实没有使用gpma的分割结果。主要是考虑到：
论文中也提到gpma的分割结果只是用来辅助判断“空白单元格”是否应合并或分割开，但是在实际的表格识别场景中，空单元格的分开与否对于表格理解的意义不是很大，整体对于评测最终的性能提升也比较有限，在推理阶段加入这部分反而会额外增加一些计算开销。但是这个模块在训练阶段的加入可以使模型收敛的效果更好，因此在训练阶段是加入了全局分割的分支。
如果想看gpma的预测mask效果，可以在推理的代码中进行相应的修改即可。

**Comment by rcx986635** [comment]
@qiaoliang6  感谢回复。明白，我理解是英文的空白单元格其实没啥用，但是中文文档中空白单元格其实还挺重要的，特别是对于某一列只有空白单元格的情况。如果我想利用gpma的mask来 生成空白单元格的bbox大概改哪里可以呢

**Comment by qiaoliang6** [comment]
> @qiaoliang6 感谢回复。明白，我理解是英文的空白单元格其实没啥用，但是中文文档中空白单元格其实还挺重要的，特别是对于某一列只有空白单元格的情况。如果我想利用gpma的mask来 生成空白单元格的bbox大概改哪里可以呢

在lgpma.py的主流程文件[lgpma.py](https://github.com/hikopensource/DAVAR-Lab-OCR/blob/main/davarocr/davarocr/davar_table/models/detectors/lgpma.py)中,  L162-L167中是有将分割结果打包一起存放在results中的，在后处理的时候把这部分取出来使用就可以。

不过我个人感觉单凭分割学习到的结果其实准确率提升有限，因为空格子里面没有明显的像素差异，而且标注起来都会很有歧义。我觉得反而可以试试一些基于虚拟表格线的方法。

**Comment by rcx986635** [comment]
@qiaoliang6 我把gpma的mask写出去看了确实在空白单元格的地方有一点但是较弱。另外能具体讲下虚拟表格线的做法和标注吗，我搜了下没找到相关参考。

**Comment by qiaoliang6** [comment]
> @qiaoliang6 我把gpma的mask写出去看了确实在空白单元格的地方有一点但是较弱。另外能具体讲下虚拟表格线的做法和标注吗，我搜了下没找到相关参考。

类似于[腾讯](https://zhuanlan.zhihu.com/p/69793742)的方案，或者是参考[这篇文章](https://ieeexplore.ieee.org/document/8977975).
