### ISSUE TITLE
error in table regocnition test_pub.py

### ISSUE THREAD

**Issue by vaskers5** [hikopensource/DAVAR-Lab-OCR#28]
Hi, when I started to run test_pub.py got this error:

Traceback (most recent call last):
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR-0.3.0/demo/table_recognition/lgpma/tools/test_pub.py", line 18, in <module>
    from davarocr.davar_common.apis import inference_model, init_model
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR-0.3.0/davarocr/davarocr/__init__.py", line 11, in <module>
    from .davar_common import *
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR-0.3.0/davarocr/davarocr/davar_common/__init__.py", line 11, in <module>
    from .models import *
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR-0.3.0/davarocr/davarocr/davar_common/models/__init__.py", line 11, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/models/dense_heads/__init__.py", line 1, in <module>
    from .anchor_free_head import AnchorFreeHead
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/models/dense_heads/anchor_free_head.py", line 8, in <module>
    from mmdet.core import multi_apply
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmcv/ops/__init__.py", line 1, in <module>
    from .bbox import bbox_overlaps
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmcv/ops/bbox.py", line 3, in <module>
    ext_module = ext_loader.load_ext('_ext', ['bbox_overlaps'])
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/site-packages/mmcv/utils/ext_loader.py", line 11, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

Process finished with exit code 1

My env packages list:

#
# Name                    Version                   Build  Channel
_libgcc_mutex             0.1                        main  
_openmp_mutex             4.5                       1_gnu  
addict                    2.4.0                    pypi_0    pypi
albumentations            0.3.2                    pypi_0    pypi
apted                     1.0.3                    pypi_0    pypi
attrs                     21.2.0                   pypi_0    pypi
beautifulsoup4            4.10.0                   pypi_0    pypi
blas                      1.0                         mkl  
bs4                       0.0.1                    pypi_0    pypi
bzip2                     1.0.8                h7b6447c_0  
ca-certificates           2021.10.26           h06a4308_2  
certifi                   2021.10.8        py37h06a4308_0  
charset-normalizer        2.0.7                    pypi_0    pypi
click                     7.1.2                    pypi_0    pypi
colorama                  0.4.4                    pypi_0    pypi
coverage                  6.1.2                    pypi_0    pypi
cudatoolkit               10.1.243             h6bb024c_0  
cycler                    0.11.0                   pypi_0    pypi
cython                    0.29.24                  pypi_0    pypi
davarocr                  0.3.0                     dev_0    <develop>
distance                  0.1.3                    pypi_0    pypi
editdistance              0.6.0                    pypi_0    pypi
ffmpeg                    4.3                  hf484d3e_0    pytorch
filelock                  3.4.0                    pypi_0    pypi
fonttools                 4.28.1                   pypi_0    pypi
freetype                  2.11.0               h70c0345_0  
giflib                    5.2.1                h7b6447c_0  
gmp                       6.2.1                h2531618_2  
gnutls                    3.6.15               he1e5248_0  
huggingface-hub           0.1.2                    pypi_0    pypi
idna                      3.3                      pypi_0    pypi
imagecorruptions          1.1.2                    pypi_0    pypi
imageio                   2.9.0                    pypi_0    pypi
imgaug                    0.3.0                    pypi_0    pypi
importlib-metadata        4.8.2                    pypi_0    pypi
iniconfig                 1.1.1                    pypi_0    pypi
intel-openmp              2021.4.0          h06a4308_3561  
joblib                    1.1.0                    pypi_0    pypi
jpeg                      9d                   h7f8727e_0  
jsonlines                 2.0.0                    pypi_0    pypi
kiwisolver                1.3.2                    pypi_0    pypi
lame                      3.100                h7b6447c_0  
lcms2                     2.12                 h3be6417_0  
ld_impl_linux-64          2.35.1               h7274673_9  
levenshtein               0.16.0                   pypi_0    pypi
libffi                    3.3                  he6710b0_2  
libgcc-ng                 9.3.0               h5101ec6_17  
libgomp                   9.3.0               h5101ec6_17  
libiconv                  1.15                 h63c8f33_5  
libidn2                   2.3.2                h7f8727e_0  
libpng                    1.6.37               hbc83047_0  
libstdcxx-ng              9.3.0               hd4cf53a_17  
libtasn1                  4.16.0               h27cfd23_0  
libtiff                   4.2.0                h85742a9_0  
libunistring              0.9.10               h27cfd23_0  
libuv                     1.40.0               h7b6447c_0  
libwebp                   1.2.0                h89dd481_0  
libwebp-base              1.2.0                h27cfd23_0  
lmdb                      1.2.1                    pypi_0    pypi
lxml                      4.6.4                    pypi_0    pypi
lz4-c                     1.9.3                h295c915_1  
markdown                  3.3.6                    pypi_0    pypi
matplotlib                3.5.0                    pypi_0    pypi
mkl                       2021.4.0           h06a4308_640  
mkl-service               2.4.0            py37h7f8727e_0  
mkl_fft                   1.3.1            py37hd3c417c_0  
mkl_random                1.2.2            py37h51133e4_0  
mmcv-full                 1.3.4                    pypi_0    pypi
mmdet                     2.11.0                   pypi_0    pypi
mmlvis                    10.5.3                   pypi_0    pypi
mmpycocotools             12.0.3                   pypi_0    pypi
model-index               0.1.11                   pypi_0    pypi
ncurses                   6.3                  h7f8727e_2  
nettle                    3.7.3                hbbd107a_1  
networkx                  2.6.3                    pypi_0    pypi
ninja                     1.10.2           py37hd09550d_3  
nltk                      3.6.5                    pypi_0    pypi
numpy                     1.21.2           py37h20f2e39_0  
numpy-base                1.21.2           py37h79a1101_0  
olefile                   0.46                     py37_0  
onnx                      1.10.2                   pypi_0    pypi
opencv-python             4.5.4.58                 pypi_0    pypi
opencv-python-headless    4.5.4.58                 pypi_0    pypi
openh264                  2.1.0                hd408876_0  
openmim                   0.1.5                    pypi_0    pypi
openssl                   1.1.1l               h7f8727e_0  
ordered-set               4.0.2                    pypi_0    pypi
packaging                 21.2                     pypi_0    pypi
pandas                    1.3.4                    pypi_0    pypi
pillow                    6.2.2                    pypi_0    pypi
pip                       21.2.2           py37h06a4308_0  
pluggy                    1.0.0                    pypi_0    pypi
polygon3                  3.0.9.1                  pypi_0    pypi
prettytable               2.4.0                    pypi_0    pypi
protobuf                  3.19.1                   pypi_0    pypi
py                        1.11.0                   pypi_0    pypi
pyclipper                 1.3.0                    pypi_0    pypi
pycocotools               2.0.2                    pypi_0    pypi
pyparsing                 2.4.7                    pypi_0    pypi
pytest                    6.2.5                    pypi_0    pypi
pytest-cov                3.0.0                    pypi_0    pypi
pytest-runner             5.3.1                    pypi_0    pypi
python                    3.7.11               h12debd9_0  
python-dateutil           2.8.2                    pypi_0    pypi
pytorch                   1.7.0           py3.7_cuda10.1.243_cudnn7.6.3_0    pytorch
pytorch-mutex             1.0                        cuda    pytorch
pytz                      2021.3                   pypi_0    pypi
pywavelets                1.2.0                    pypi_0    pypi
pyyaml                    6.0                      pypi_0    pypi
rapidfuzz                 1.8.2                    pypi_0    pypi
readline                  8.1                  h27cfd23_0  
regex                     2021.11.10               pypi_0    pypi
requests                  2.26.0                   pypi_0    pypi
sacremoses                0.0.46                   pypi_0    pypi
scikit-image              0.18.3                   pypi_0    pypi
scikit-learn              1.0.1                    pypi_0    pypi
scipy                     1.7.2                    pypi_0    pypi
seqeval                   1.2.2                    pypi_0    pypi
setuptools                58.0.4           py37h06a4308_0  
setuptools-scm            6.3.2                    pypi_0    pypi
shapely                   1.8.0                    pypi_0    pypi
sharedarray               3.2.1                    pypi_0    pypi
six                       1.16.0             pyhd3eb1b0_0  
sklearn                   0.0                      pypi_0    pypi
soupsieve                 2.3.1                    pypi_0    pypi
sqlite                    3.36.0               hc218d9a_0  
tabulate                  0.8.9                    pypi_0    pypi
terminaltables            3.1.0                    pypi_0    pypi
threadpoolctl             3.0.0                    pypi_0    pypi
tifffile                  2021.11.2                pypi_0    pypi
tk                        8.6.11               h1ccaba5_0  
tokenizers                0.10.3                   pypi_0    pypi
toml                      0.10.2                   pypi_0    pypi
tomli                     1.2.2                    pypi_0    pypi
torchvision               0.8.1                py37_cu101    pytorch
tqdm                      4.62.3                   pypi_0    pypi
transformers              4.12.5                   pypi_0    pypi
typing_extensions         3.10.0.2           pyh06a4308_0  
urllib3                   1.26.7                   pypi_0    pypi
warpctc-pytorch           0.1                      pypi_0    pypi
wcwidth                   0.2.5                    pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1  
xz                        5.2.5                h7b6447c_0  
yapf                      0.31.0                   pypi_0    pypi
zipp                      3.6.0                    pypi_0    pypi
zlib                      1.2.11               h7b6447c_3  
zstd                      1.4.9                haebb681_0

**Comment by vaskers5** [comment]
also i have this error, if I build mmidet by offical instructions and after run the scrpit:
Traceback (most recent call last):
  File "demo/table_recognition/lgpma/tools/test_pub.py", line 19, in <module>
    from davarocr.davar_common.apis import inference_model, init_model
  File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/__init__.py", line 11, in <module>
    from .davar_common import *
  File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/__init__.py", line 11, in <module>
    from .models import *
  File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/models/__init__.py", line 16, in <module>
    from .builder import CONNECTS, EMBEDDING
  File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/models/builder.py", line 13, in <module>
    from mmdet.models.builder import build
ImportError: cannot import name 'build' from 'mmdet.models.builder' (/home/vaskers5/miniconda3/envs/dava/lib/python3.7/site-packages/mmdet/models/builder.py

**Comment by qiaoliang6** [comment]
> also i have this error, if I build mmidet by offical instructions and after run the scrpit: Traceback (most recent call last): File "demo/table_recognition/lgpma/tools/test_pub.py", line 19, in from davarocr.davar_common.apis import inference_model, init_model File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/**init**.py", line 11, in from .davar_common import * File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/**init**.py", line 11, in from .models import * File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/models/**init**.py", line 16, in from .builder import CONNECTS, EMBEDDING File "/home/vaskers5/projects/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/models/builder.py", line 13, in from mmdet.models.builder import build ImportError: cannot import name 'build' from 'mmdet.models.builder' (/home/vaskers5/miniconda3/envs/dava/lib/python3.7/site-packages/mmdet/models/builder.py


I have check the latest mmdet2.18.0, in "mmdet/models/builder.py", there is no method of 'build', but version-2.11.0 has.

I think you might use anthor version of mmdet and you may check it by the command of "print(mmdet.__version__)".

**Comment by vaskers5** [comment]
Сan you please suggest all the author's versions of the packages?
I just can't find a complete list of dependencies for a working build in your project

**Comment by qiaoliang6** [comment]
Thank you for your suggestion. We will consider to add a requirement list.

For now, all dependencies can be installed by the setup.sh script, where the versions of some specific packages have already been labeld.

**Comment by vaskers5** [comment]
also i have the same error with mmdet==2.11.0;

Traceback (most recent call last):
  File "demo/table_recognition/lgpma/tools/test_pub.py", line 19, in <module>
    from davarocr.davar_common.apis import inference_model, init_model
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR/davarocr/davarocr/__init__.py", line 11, in <module>
    from .davar_common import *
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/__init__.py", line 11, in <module>
    from .models import *
  File "/home/vaskers5/projects/Genotek/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/models/__init__.py", line 11, in <module>
    from mmdet.models.builder import (BACKBONES, DETECTORS, HEADS, LOSSES, NECKS,
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/models/__init__.py", line 6, in <module>
    from .dense_heads import *  # noqa: F401,F403
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/models/dense_heads/__init__.py", line 1, in <module>
    from .anchor_free_head import AnchorFreeHead
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/models/dense_heads/anchor_free_head.py", line 8, in <module>
    from mmdet.core import multi_apply
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/core/__init__.py", line 2, in <module>
    from .bbox import *  # noqa: F401, F403
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/__init__.py", line 7, in <module>
    from .samplers import (BaseSampler, CombinedSampler,
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/samplers/__init__.py", line 9, in <module>
    from .score_hlr_sampler import ScoreHLRSampler
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmdet/core/bbox/samplers/score_hlr_sampler.py", line 2, in <module>
    from mmcv.ops import nms_match
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmcv/ops/__init__.py", line 2, in <module>
    from .assign_score_withk import assign_score_withk
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmcv/ops/assign_score_withk.py", line 5, in <module>
    ext_module = ext_loader.load_ext(
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/site-packages/mmcv/utils/ext_loader.py", line 13, in load_ext
    ext = importlib.import_module('mmcv.' + name)
  File "/home/vaskers5/miniconda3/envs/davar/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
ModuleNotFoundError: No module named 'mmcv._ext'

**Comment by qiaoliang6** [comment]
> ModuleNotFoundError: No module named 'mmcv._ext'

What is the mmcv-full version? 

You may uninstall current mmcv and re-install it in a correct version:
     
    pip uninstall mmcv-full
    pip uninstall mmcv
    pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/{cu_version}/{torch_version}/index.html

For example:
    pip install mmcv-full==1.3.4 -f https://download.openmmlab.com/mmcv/dist/cu102/torch1.8.0/index.html

**Comment by vaskers5** [comment]
Thank you guys

**Comment by jigsawcoder** [comment]
Can anyone specify please, which version of PyTorch, MMCV and MMDET can be used to run test_pub.py to infer custom images from LGPMA model??

**Comment by zhangqiqi1228** [comment]
> Can anyone specify please, which version of PyTorch, MMCV and MMDET can be used to run test_pub.py to infer custom images from LGPMA model??

@jigsawcoder as the author mentioned in other issue, mmcv-full==1.3.4 and mmdet=2.11.0. 
But I still got the "ModuleNotFoundError: No module named 'mmcv._ext'" error with these versions.
