### ISSUE TITLE
Mismatch between the number of bounding boxes and html tags from LGPMA

### ISSUE THREAD

**Issue by setotaku0515** [hikopensource/DAVAR-Lab-OCR#29]
Hi,

Thank you for sharing your wonderful source code and pre-trained model.
Is it possible that mismatch is occurred between the number of bounding boxes and it showed by html tags?

Best regards 👍

**Comment by qiaoliang6** [comment]
The html result is generated according to the predicted bounding boxes by the post-processing script, so the number should be matched if the bounding boxes are correctly predicted.  Mismatch happens when the predicted bounding boxes cannot form a table.

**Comment by setotaku0515** [comment]
Thank you for your detailed reply.
I encountered the mismatch mentioned above, but now I understand why that happened.
