### ISSUE TITLE
OSError: no file with expected extension

### ISSUE THREAD

**Issue by GrayChan813** [hikopensource/DAVAR-Lab-OCR#31]
Traceback (most recent call last):
  File "/home/pengfan/anaconda3/envs/LGPMA/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/pengfan/DAVAR-Lab-OCR/davarocr/davarocr/davar_table/datasets/pipelines/gpma_data.py", line 50, in __init__
    lib = ctl.load_library(lib_name, lib_dir)
  File "/home/pengfan/anaconda3/envs/LGPMA/lib/python3.7/site-packages/numpy/ctypeslib.py", line 153, in load_library
    raise OSError("no file with expected extension")
OSError: no file with expected extension

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/pengfan/anaconda3/envs/LGPMA/lib/python3.7/site-packages/mmcv/utils/registry.py", line 52, in build_from_cfg
    return obj_cls(**args)
  File "/home/pengfan/DAVAR-Lab-OCR/davarocr/davarocr/davar_common/datasets/davar_custom.py", line 135, in __init__
    self.pipeline = Compose(pipeline)
  File "/home/pengfan/anaconda3/envs/LGPMA/lib/python3.7/site-packages/mmdet/datasets/pipelines/compose.py", line 22, in __init__
    transform = build_from_cfg(transform, PIPELINES)
  File "/home/pengfan/anaconda3/envs/LGPMA/lib/python3.7/site-packages/mmcv/utils/registry.py", line 55, in build_from_cfg
    raise type(e)(f'{obj_cls.__name__}: {e}')
OSError: GPMADataGeneration: no file with expected extension

**Comment by GrayChan813** [comment]
name: LGPMA
channels:
  - pytorch
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - blas=1.0=mkl
  - ca-certificates=2021.10.26=h06a4308_2
  - certifi=2021.10.8=py37h06a4308_0
  - cudatoolkit=10.1.243=h6bb024c_0
  - freetype=2.11.0=h70c0345_0
  - giflib=5.2.1=h7b6447c_0
  - intel-openmp=2021.4.0=h06a4308_3561
  - jpeg=9d=h7f8727e_0
  - lcms2=2.12=h3be6417_0
  - ld_impl_linux-64=2.35.1=h7274673_9
  - libffi=3.3=he6710b0_2
  - libgcc-ng=9.1.0=hdf63c60_0
  - libpng=1.6.37=hbc83047_0
  - libstdcxx-ng=9.1.0=hdf63c60_0
  - libtiff=4.2.0=h85742a9_0
  - libwebp=1.2.0=h89dd481_0
  - libwebp-base=1.2.0=h27cfd23_0
  - lz4-c=1.9.3=h295c915_1
  - mkl=2021.4.0=h06a4308_640
  - mkl-service=2.4.0=py37h7f8727e_0
  - mkl_fft=1.3.1=py37hd3c417c_0
  - mkl_random=1.2.2=py37h51133e4_0
  - ncurses=6.3=h7f8727e_2
  - ninja=1.10.2=py37hd09550d_3
  - olefile=0.46=py37_0
  - openssl=1.1.1l=h7f8727e_0
  - pip=21.2.2=py37h06a4308_0
  - python=3.7.11=h12debd9_0
  - pytorch=1.6.0=py3.7_cuda10.1.243_cudnn7.6.3_0
  - readline=8.1=h27cfd23_0
  - setuptools=58.0.4=py37h06a4308_0
  - six=1.16.0=pyhd3eb1b0_0
  - sqlite=3.36.0=hc218d9a_0
  - tk=8.6.11=h1ccaba5_0
  - torchvision=0.7.0=py37_cu101
  - wheel=0.37.0=pyhd3eb1b0_1
  - xz=5.2.5=h7b6447c_0
  - zlib=1.2.11=h7b6447c_3
  - zstd=1.4.9=haebb681_0
  - pip:
    - addict==2.4.0
    - albumentations==0.3.2
    - apted==1.0.3
    - attrs==21.2.0
    - beautifulsoup4==4.10.0
    - bs4==0.0.1
    - charset-normalizer==2.0.7
    - click==8.0.3
    - coverage==6.1.2
    - cycler==0.11.0
    - cython==0.29.24
    - distance==0.1.3
    - editdistance==0.6.0
    - filelock==3.4.0
    - fonttools==4.28.2
    - huggingface-hub==0.1.2
    - idna==3.3
    - imagecorruptions==1.1.2
    - imageio==2.9.0
    - imgaug==0.3.0
    - importlib-metadata==4.8.2
    - iniconfig==1.1.1
    - joblib==1.1.0
    - jsonlines==2.0.0
    - kiwisolver==1.3.2
    - levenshtein==0.16.0
    - lmdb==1.2.1
    - lxml==4.6.4
    - matplotlib==3.5.0
    - mmcv-full==1.3.4
    - mmdet==2.11.0
    - mmlvis==10.5.3
    - mmpycocotools==12.0.3
    - networkx==2.6.3
    - nltk==3.6.5
    - numpy==1.20.0
    - onnx==1.10.2
    - opencv-python==4.5.4.60
    - opencv-python-headless==4.5.4.60
    - packaging==21.3
    - pillow==6.2.2
    - pluggy==1.0.0
    - polygon3==3.0.9.1
    - prettytable==2.4.0
    - protobuf==3.19.1
    - py==1.11.0
    - pyclipper==1.3.0
    - pyparsing==3.0.6
    - pytest==6.2.5
    - pytest-cov==3.0.0
    - pytest-runner==5.3.1
    - python-dateutil==2.8.2
    - pywavelets==1.2.0
    - pyyaml==6.0
    - rapidfuzz==1.8.3
    - regex==2021.11.10
    - requests==2.26.0
    - sacremoses==0.0.46
    - scikit-image==0.18.3
    - scikit-learn==1.0.1
    - scipy==1.7.2
    - seqeval==1.2.2
    - setuptools-scm==6.3.2
    - shapely==1.8.0
    - sharedarray==3.2.1
    - sklearn==0.0
    - soupsieve==2.3.1
    - terminaltables==3.1.0
    - threadpoolctl==3.0.0
    - tifffile==2021.11.2
    - tokenizers==0.10.3
    - toml==0.10.2
    - tomli==1.2.2
    - tqdm==4.62.3
    - transformers==4.12.5
    - typing-extensions==4.0.0
    - urllib3==1.26.7
    - warpctc-pytorch==0.1
    - wcwidth==0.2.5
    - yapf==0.31.0
    - zipp==3.6.0
prefix: /home/pengfan/anaconda3/envs/LGPMA

**Comment by GrayChan813** [comment]
您好：

        仔细拜读了贵机构的文章，觉得你们的工作非常有意义，感谢你们对这个项目的开源。
        最近我也在研究关于表格识别方向的内容，在运行LGPMA训练的demo时遇到了上述的错误。查阅了github上相关的issues，我去查看了相应的lib里面确实没有.so的文件。重新运行setup.sh也并没有.so文件的生成，想向您请教一下应该怎么解决这个问题呢？

感谢！

**Comment by qiaoliang6** [comment]
> 您好：
> 
> ```
>     仔细拜读了贵机构的文章，觉得你们的工作非常有意义，感谢你们对这个项目的开源。
>     最近我也在研究关于表格识别方向的内容，在运行LGPMA训练的demo时遇到了上述的错误。查阅了github上相关的issues，我去查看了相应的lib里面确实没有.so的文件。重新运行setup.sh也并没有.so文件的生成，想向您请教一下应该怎么解决这个问题呢？
> ```
> 
> 感谢！

是否是执行setup.sh路径的问题导致。
生成相关.so文件的命令位于Davar-Lab-OCR/davarocr/setup.sh L17:

    g++ -shared -o ./davarocr/davar_table/datasets/pipelines/lib/gpma_data.so -fPIC ./davarocr/davar_table/datasets/pipelines/lib/gpma_data.cpp `pkg-config --cflags --libs opencv`

可以命令行单独执行一下该命令，看是否可以正常编译。

**Comment by GrayChan813** [comment]
感谢你的耐心解答！问题已经解决了！期待您们更好的工作！

**Comment by SdwHorizon** [comment]
> 感谢你的耐心解答！问题已经解决了！期待您们更好的工作！

你好，问题是怎么解决的？我也遇到同样的问题

**Comment by GrayChan813** [comment]
> > 感谢你的耐心解答！问题已经解决了！期待您们更好的工作！
> 
> 你好，问题是怎么解决的？我也遇到同样的问题

在Davar-Lab-OCR/davarocr路径下面还有一个setup.sh文件，需要对这个文件执行bash setup.sh命令

**Comment by SdwHorizon** [comment]
> 



> > > 感谢你的耐心解答！问题已经解决了！期待您们更好的工作！
> > 
> > 
> > 你好，问题是怎么解决的？我也遇到同样的问题
> 
> 在Davar-Lab-OCR/davarocr路径下面还有一个setup.sh文件，需要对这个文件执行bash setup.sh命令

感谢您的回复！现在的代码中 Davar-Lab-OCR/davarocr 路径下没有 setup.sh 文件。方便发我下吗？非常感谢！
![image](https://user-images.githubusercontent.com/52166214/149049898-42be9159-9352-49ac-8ebc-e1303e742b15.png)

**Comment by Athena233** [comment]
> > 
> 
> > > > 感谢你的耐心解答！问题已经解决了！期待您们更好的工作！
> > > 
> > > 
> > > 你好，问题是怎么解决的？我也遇到同样的问题
> > 
> > 
> > 在Davar-Lab-OCR/davarocr路径下面还有一个setup.sh文件，需要对这个文件执行bash setup.sh命令
> 
> 感谢您的回复！现在的代码中 Davar-Lab-OCR/davarocr 路径下没有 setup.sh 文件。方便发我下吗？非常感谢！ ![image](https://user-images.githubusercontent.com/52166214/149049898-42be9159-9352-49ac-8ebc-e1303e742b15.png)

请问你解决了吗，我也没找到呢
