### ISSUE TITLE
请问LGPMA如何调用text recognition module得到完整的结果

### ISSUE THREAD

**Issue by le8888e** [hikopensource/DAVAR-Lab-OCR#34]
LGPMA推理可以得到表格的HTML标签result['html']和所有cell框的位置result['bboxes']。您在README里提到The release model only contains structure-level result. You may use the text recognition module for the complete result. 请问要如何调用text recognition module得到complete result？将result['bboxes']里的每个框顺次输入OCR识别模块，得到的文字顺次填入HTML标签的<td> </td>中间吗？
谢谢解答

**Comment by qiaoliang6** [comment]
一种简单的方式就是直接将results['bboxes']的框在crop出原图中对应区域，然后送入OCR识别模块进行识别。但是注意，这里results['bboxes']中得到的是“对齐单元格”的框，意味着crop的小图中有大量空白，所以直接识别性能可能会不太好。比较好的做法就是把模型预测的bboxes框中的mask取出来做外接矩形，然后再去识别。目前的后处理模块中没有直接输出mask的值，但是模型实际上是由预测这个值的，可以在davar_table/core/post_processing/post_lgpma.py中L102-115中获取result中其他元素得到。

另外注意，直接用davar_rcg中提供的训练好的模型可能效果不会特别好，因为是基于自然场景的数据训出来的，要是需要好的性能，还是得把表格中的文字都抠图存下来然后finetune一个新的识别模型。

**Comment by le8888e** [comment]
@qiaoliang6 谢谢解答。我现在是将整张图输入到OCR模型里，再将每个文本框text_bbox和单元格cell_bbox计算IOU，将文本框匹配到对应的单元格上。有一个疑问，请问后处理代码post_lgpma.py里最后几行
            html_str_rec, html_text_rec = area_to_html(arearec, labels, texts_tokens)
            table_result['html'] = format_html(html_str_rec, html_text_rec)
            table_result['bboxes'] = bboxes
            table_result['labels'] = labels
            table_results.append(table_result)
这里的labels代表什么？谢谢

**Comment by qiaoliang6** [comment]
因为PubTabNet这个数据集对单元格区分了head还是body，所以这里的mask-rcnn模型同时做了一个多类别的检测任务，没记错的话label=0应该指的是head类，1是body类，具体可能得再check下。

**Comment by le8888e** [comment]
@qiaoliang6 明白了。我测试了一下LGPMA对一些大的单元格（如附件）的cell检测效果不太好，一个大格子会被检测成很多小格子，而且会串格。我猜是因为PubTabNet数据集都是小格子，模型没见过这种大格子。请问您有什么解决思路吗？谢谢
![table_0](https://user-images.githubusercontent.com/34771253/146525700-1e3f00e3-6b1b-46f9-88d8-02a430f7db4a.png)

**Comment by qiaoliang6** [comment]
这个是因为这个模型只在PubTabNet上训过，如果该数据集有标注的话，直接在这个场景训练一下就可以了。

未来我们会考虑发布一个通用的在多种场景下训练过的模型。

**Comment by le8888e** [comment]
@qiaoliang6 感谢解答！期待有表格标注工具和通用模型的更新
