### ISSUE TITLE
没有gpma_data.so

### ISSUE THREAD

**Issue by le8888e** [hikopensource/DAVAR-Lab-OCR#35]
DAVAR-Lab-OCR/blob/main/davarocr/davarocr/davar_table/datasets/pipelines/gpma_data.py第43行：
        if lib_name is None or not os.path.isfile(os.path.join(lib_dir, lib_name)):
            # Using default lib
            cur_path = os.path.realpath(__file__)
            lib_dir = cur_path.replace('\\', '/').split('/')[:-1]
            lib_dir = "/".join(lib_dir) + '/lib'
            lib_name = "gpma_data.so"
        if lib_name is not None and lib_dir is not None:
            lib = ctl.load_library(lib_name, lib_dir)

对应的目录DAVAR-Lab-OCR/davarocr/davarocr/davar_table/datasets/pipelines/lib里没有gpma_data.so，导致训练报错

请问如何解决？谢谢

**Comment by qiaoliang6** [comment]
参考一些issue #31
