### ISSUE TITLE
PubTabNet datalist失效

### ISSUE THREAD

**Issue by zhiminzhang0830** [hikopensource/DAVAR-Lab-OCR#38]
显示PubTabNet datalist失效了，能否重新放一个链接

**Comment by qiaoliang6** [comment]
> 显示PubTabNet datalist失效了，能否重新放一个链接

抱歉，新的链接已经更新了

**Comment by zhiminzhang0830** [comment]
> > 显示PubTabNet datalist失效了，能否重新放一个链接
> 
> 抱歉，新的链接已经更新了
好的，谢谢
