### ISSUE TITLE
Failed building wheel for mmpycocotools

### ISSUE THREAD

**Issue by itaizy** [hikopensource/DAVAR-Lab-OCR#39]
你好，感谢你们公开项目源码，我在安装的时候，遇到了如下问题。 系统环境是通过conda创建的一个全新的Python环境

Building wheel for mmpycocotools (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/.conda/envs/py3.6/bin/python -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-ulxsr6m2/mmpycocotools_bbc7125ac5c24f7eba50e936fed7b267/setup.py'"'"'; __file__='"'"'/tmp/pip-install-ulxsr6m2/mmpycocotools_bbc7125ac5c24f7eba50e936fed7b267/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-9y2p8ww8
       cwd: /tmp/pip-install-ulxsr6m2/mmpycocotools_bbc7125ac5c24f7eba50e936fed7b267/
  Complete output (23 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.6
  creating build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/coco.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/mask.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/cocoeval.py -> build/lib.linux-x86_64-3.6/pycocotools
  copying pycocotools/__init__.py -> build/lib.linux-x86_64-3.6/pycocotools
  running build_ext
  building 'pycocotools._mask' extension
  creating build/temp.linux-x86_64-3.6
  creating build/temp.linux-x86_64-3.6/common
  creating build/temp.linux-x86_64-3.6/pycocotools
  gcc -pthread -B /home/ubuntu/.conda/envs/py3.6/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/.local/lib/python3.6/site-packages/numpy/core/include -Icommon -I/home/ubuntu/.conda/envs/py3.6/include/python3.6m -c common/maskApi.c -o build/temp.linux-x86_64-3.6/common/maskApi.o
  common/maskApi.c: In function ‘rleToBbox’:
  common/maskApi.c:141:31: warning: ‘xp’ may be used uninitialized in this function [-Wmaybe-uninitialized]
         if(j%2==0) xp=x; else if(xp<x) { ys=0; ye=h-1; }
                                 ^
  gcc -pthread -B /home/ubuntu/.conda/envs/py3.6/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/ubuntu/.local/lib/python3.6/site-packages/numpy/core/include -Icommon -I/home/ubuntu/.conda/envs/py3.6/include/python3.6m -c pycocotools/_mask.c -o build/temp.linux-x86_64-3.6/pycocotools/_mask.o
  gcc: error: pycocotools/_mask.c: No such file or directory
  error: command 'gcc' failed with exit status 1
  ----------------------------------------
  ERROR: Failed building wheel for mmpycocotools

**Comment by qiaoliang6** [comment]
应该是最近官方停止了对mmpycocotools的支持https://github.com/open-mmlab/mmdetection/pull/6838

可以试一下装成pycocotools是否可以正常执行

**Comment by itaizy** [comment]
> 应该是最近官方停止了对mmpycocotools的支持[open-mmlab/mmdetection#6838](https://github.com/open-mmlab/mmdetection/pull/6838)
> 
> 可以试一下装成pycocotools是否可以正常执行

酷！解决问题了，太强了。但是咱们现在有训练好的模型吗？在 demo 目录下的 table_recognition 里面可以直接做 inference 吗？demo/table_recognition/lgpma/tools/test_pub.py 和引用的 demo/table_recognition/lgpma/configs/lgpma_pub.py 里面有很多的目录都是需要配置的呢。

**Comment by qiaoliang6** [comment]
demo中提供的模型是在PubTabNet上训练好的模型，可以直接在该数据集上做inference，在其他数据上性能可能会受影响。只需要把test_pub.py脚本中的数据集路径改为本地的真实路径即可。

如果要在自己的数据集上训练模型，需要配置config中的路径。
