### ISSUE TITLE
inference images in trie

### ISSUE THREAD

**Issue by sivaguru-pat** [hikopensource/DAVAR-Lab-OCR#40]
i have tried using test.sh provided in the repo which works fine on the images with gt information.
how to infer other images with this model

**Comment by DAVAR-Lab** [comment]
Modify the test images paths data['test'] in the config. 

You may also inference single image using the apis that provided in davarocr/davar_common/apis/inference. You can refer to demo/text_detection/east/test.py

**Comment by sivaguru-pat** [comment]
tried single image inference, facing this error 
![Screenshot from 2021-12-27 13-14-51](https://user-images.githubusercontent.com/46225496/147448532-6f24cd38-2bae-4cc7-aa4a-6422a517ae51.png)

**Comment by DAVAR-Lab** [comment]
Infering trie_gt.py model needs the ground-truth of of the OCR results，which should be contained in the datalist.json.

 The end-to-end model has not been released yet.

**Comment by sivaguru-pat** [comment]
can you suggest a model to create that json?

**Comment by DAVAR-Lab** [comment]
> can you suggest a model to create that json?

There are several text detection/ recognition/ spotting methods contained in davarocr, but all the released models are only trained on the  specific corresponding datasets. If you want to use them, you may need to finetune them in your own dataset.

For general OCR tools,  you may use some OCR engines like  tesseract or PaddlePaddle to generate the OCR results.
