### ISSUE TITLE
LGPMA training consume unstable

### ISSUE THREAD

**Issue by somewhat998** [hikopensource/DAVAR-Lab-OCR#42]
While training lgpma with my own data, the memory and time consume are very unstable. Could you tell me how to improve it?
![image](https://user-images.githubusercontent.com/31963320/147638725-95402ef4-845c-4b7c-96f2-15601f1bd2f5.png)
![image](https://user-images.githubusercontent.com/31963320/147638830-23ad18a3-73b4-41b9-9d76-6701ff314a22.png)

**Comment by tucachmo2202** [comment]
hi, @somewhat998. Could you tell me how to create your own dataset? Thanks.
