### ISSUE TITLE
How to get HTML with text in Table recognition 

### ISSUE THREAD

**Issue by sindhurk** [hikopensource/DAVAR-Lab-OCR#48]
I got the html tags, bboxes of cell and labels. I also used the bboxes to OCR the text in the cell.
How do I use the text to fill in the HTML? given that the table cells are not in order and some cells can also be empty values

**Comment by ZaishengLi** [comment]
You can refer to line 139-141 in 'davarocr/davar_table/core/post_processing/post_lgpma.py'. If texts_tokens are the ocr results of each bboxes defined in line 114,  the final html will be available.

**Comment by ZaishengLi** [comment]
> I got the html tags, bboxes of cell and labels. I also used the bboxes to OCR the text in the cell. How do I use the text to fill in the HTML? given that the table cells are not in order and some cells can also be empty values
You can refer to line 139-141 in 'davarocr/davar_table/core/post_processing/post_lgpma.py'. If texts_tokens are the ocr results of each bboxes defined in line 114, the final html will be available.

**Comment by ZaishengLi** [comment]
> You can refer to line 139-141 in 'davarocr/davar_table/core/post_processing/post_lgpma.py'. If texts_tokens are the ocr results of each bboxes defined in line 114, the final html will be available.

1

**Comment by sindhurk** [comment]
thanks! this helps

**Comment by jigsawcoder** [comment]
> 

I think the line you mentioned is from the old version of the code, can you please update the line number for further reference?

Thank you

**Comment by jigsawcoder** [comment]
> 

Also, can you please tell me what exactly are the inputs of the post_processing of lgpma. I have gone through the code  
and it says the inputs are as follows:

batch_result(list(Tensor)): prediction results,
like [(box_result, seg_result, local_pyramid_masks, global_pyramid_masks), ...] 
**kwargs: other parameters 

So I have few questions regarding this, 
1) From where can we get the batch_results?
2) Are the results from the lgpma model (which contains html_tags, bboxes and labels) same as these batch_results?
