### ISSUE TITLE
Text-layout inference

### ISSUE THREAD

**Issue by javierztl** [hikopensource/DAVAR-Lab-OCR#49]
Thank you very much for your great work to merge CNN and NLP.
Can you please share your [test_pipeline ](https://github.com/hikopensource/DAVAR-Lab-OCR/blob/2c518763134331cdaeb46d12aaec61fa3b0e6a02/demo/text_layout/VSR/PubLayNet/config/publaynet_x101.py#L273)during inference or prediction? As the current pipeline is for evaluation.

**Comment by hik-zhangpeng** [comment]
The test pipeline code will be published soon.

**Comment by hik-zhangpeng** [comment]
Well, i think what you mean by "test_pipeline" is re-writing codes to preprocess the image (resize, pad, normalize...) and text (tokenize...) separately?
However, all these code are already in the [code](https://github.com/hikopensource/DAVAR-Lab-OCR/tree/main/davarocr/davar_layout/datasets). And it's more convenient to use the current pipeline.

If you still have any doubt, feel free to post.

**Comment by qiaoliang6** [comment]
> The test pipeline code will be published soon.

The code has been updated in [e14ed62](https://github.com/hikopensource/DAVAR-Lab-OCR/commit/e14ed6268f39e2efd7afd6fd4e94f3a1a0f52cf0)
