### ISSUE TITLE
训练VSR的数据格式

### ISSUE THREAD

**Issue by shihuai** [hikopensource/DAVAR-Lab-OCR#50]
![image](https://user-images.githubusercontent.com/4709173/148712664-1d4f8256-a116-43a0-865b-395ad2d34a7b.png)
上面这张图是代码里VSR模块中提供的一个标注文件，想问一下上面的这些字段中，cares字段作用是什么呢？还有一个就是labels字段中，标签为0是指页眉页脚吗？

**Comment by hik-zhangpeng** [comment]
cares：list中对应1的标注参与loss计算，对应0的不参与。

content_ann中labels为0表示未标注内容（即与content_ann2/ 官方提供的版面级标注未match上的内容）。

**Comment by shihuai** [comment]
> 
好的，谢谢！！！
