### ISSUE TITLE
some problem about inference of LGPMA?

### ISSUE THREAD

**Issue by cv-small-snails** [hikopensource/DAVAR-Lab-OCR#52]
where the code about Aligned Bounding Box Refine as described in paper 3.6? 
The code published just use the result of Aligned Bounding Box Detection?

**Comment by qiaoliang6** [comment]
> where the code about Aligned Bounding Box Refine as described in paper 3.6? The code published just use the result of Aligned Bounding Box Detection?

During the re-implementation, we find that using GPMA as an auxiliary training branch that is not involved in the inference stage could also achieve similar performance with higher running speed.  So we simplify this stage and remove the rescore process in the current version of code.

**Comment by cv-small-snails** [comment]
OK, I undertand, thank you
