### ISSUE TITLE
Error when building warpctc

### ISSUE THREAD

**Issue by imMid-Star** [hikopensource/DAVAR-Lab-OCR#53]
[ 11%] Building NVCC (Device) object CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o
In file included from /usr/local/cuda-10.0/include/cuda_runtime.h:83,
                 from <command-line>:
/usr/local/cuda-10.0/include/crt/host_config.h:129:2: error: #error -- unsupported GNU version! gcc versions later than 7 are not supported!
  129 | #error -- unsupported GNU version! gcc versions later than 7 are not supported!
      |  ^~~~~
CMake Error at warpctc_generated_reduce.cu.o.cmake:220 (message):
  Error generating
  /1/dl_pzx/DAVAR-Lab-OCR/davarocr/davar_rcg/third_party/warp-ctc-pytorch_bindings/build/CMakeFiles/warpctc.dir/src/./warpctc_generated_reduce.cu.o

CMakeFiles/warpctc.dir/build.make:89: recipe for target 'CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o' failed
make[2]: *** [CMakeFiles/warpctc.dir/src/warpctc_generated_reduce.cu.o] Error 1
CMakeFiles/Makefile2:152: recipe for target 'CMakeFiles/warpctc.dir/all' failed
make[1]: *** [CMakeFiles/warpctc.dir/all] Error 2
Makefile:148: recipe for target 'all' failed
make: *** [all] Error 2

How can l solve this problem?

**Comment by imMid-Star** [comment]
Except changing the version of gcc, is there any other solution?

**Comment by qiaoliang6** [comment]
Warpctc is a third party package that is implemented relied on certain environment. If you do not need the algorithm using in warpctc, you may simply command the code like 'import warptctc ' and it would not influence others algorithms.
