### ISSUE TITLE
davar_resize对模型精度的影响

### ISSUE THREAD

**Issue by SilverBach805** [hikopensource/DAVAR-Lab-OCR#54]
还有一个问题，就是因为我们机器的显存不太够的原因，我将davar_resize这个参数由img_scale=[(360, 480), (960, 1080)]调整为了img_scale=[(360, 480), (540, 720)]，不知道这样将图片的尺寸随机缩小一些后，会不会对模型的推理精度有较大的影响？谢谢！

**Comment by qiaoliang6** [comment]
这个跟具体的数据集本身的数据尺度有关系，你的改动只是让模型训练的时候扩增的范围缩小一点，在推理的时候只要模型是从一个见过的尺度去做推理精度的影响就不会很大。

**Comment by SilverBach805** [comment]
好的，谢谢您的回复，期待你们更多有价值的工作！
