### ISSUE TITLE
Is it possible to train MANGO without using character-level annotation?

### ISSUE THREAD

**Issue by to-lie-down** [hikopensource/DAVAR-Lab-OCR#57]
Is it possible to train MANGO without using character-level annotation? Just use the word-level annotation.

**Comment by qiaoliang6** [comment]
You can finetune the model (using the pretrained model) on any dataset without using character-level annotation.
If the dataset is relatively simple, the model can also be trained from scratch only using word-level annoation.

**Comment by to-lie-down** [comment]
Thank you for your reply!

 Can you provide the annotations files of SynthText and SynthCurve:
            '/path/to/datalist/synthtext_80w.json',
            '/path/to/datalist/train_syntext_word_eng.json',
            '/path/to/datalist/train_emcs_imgs.json',

**Comment by to-lie-down** [comment]
@qiaoliang6

**Comment by qiaoliang6** [comment]
> Thank you for your reply!
> 
> Can you provide the annotations files of SynthText and SynthCurve: '/path/to/datalist/synthtext_80w.json', '/path/to/datalist/train_syntext_word_eng.json', '/path/to/datalist/train_emcs_imgs.json',

We have just uploaded all these formated datalist in HikOne. See [demo/text_spotting/datalist/readme.md](https://github.com/hikopensource/DAVAR-Lab-OCR/tree/main/demo/text_spotting/datalist)

**Comment by to-lie-down** [comment]
Thank you!
