### ISSUE TITLE
assert results['classes_config'] is not None

### ISSUE THREAD

**Issue by aaferrero** [hikopensource/DAVAR-Lab-OCR#59]
训练lgpma表格结构识别时,代码提示这个错误,classes_config怎么设置

**Comment by qiaoliang6** [comment]
这个可能是你的datalist中的annotations['labels']存储的是str类型，需要通过classes_config进行转码，改成int类型存储就行

**Comment by aaferrero** [comment]
Returns:
        dict:   "content_ann" in ours training dataset (davar format), like:
                "content_ann": {
                                "bboxes": [[11, 5, 33, 14],
                                           [202, 5, 225, 14],
                                           [14, 27, 30, 35],
                                           [199, 27, 229, 35]],
                                "texts": ["Trait", "Mean", "SCS", "- 0.1024"],
                                "texts_tokens": [["<b>", "T", "r", "a", "i", "t", "</b>"],
                                                 ["<b>", "M", "e", "a", "n", "</b>"],
                                                 ["S", "C", "S"],
                                                 ["-", " ", "0", ".", "1", "0", "2", "4"]],
                                "cells": [[0,0,0,0],
                                          [0,1,0,1],
                                          [1,0,1,0],
                                          [1,1,1,1]],
                                "labels": [["t-head"],
                                           ["t-head"],
                                           ["t-head"],
                                           ["t-head"]]
                 }

DAVAR中'labels'本身是str类型，怎么通过class_config进行转码呢，这工程中我找了很久没有找到配置class_config的配置文件或者配置。

**Comment by qiaoliang6** [comment]
> Returns: dict: "content_ann" in ours training dataset (davar format), like: "content_ann": { "bboxes": [[11, 5, 33, 14], [202, 5, 225, 14], [14, 27, 30, 35], [199, 27, 229, 35]], "texts": ["Trait", "Mean", "SCS", "- 0.1024"], "texts_tokens": [["", "T", "r", "a", "i", "t", ""], ["", "M", "e", "a", "n", ""], ["S", "C", "S"], ["-", " ", "0", ".", "1", "0", "2", "4"]], "cells": [[0,0,0,0], [0,1,0,1], [1,0,1,0], [1,1,1,1]], "labels": [["t-head"], ["t-head"], ["t-head"], ["t-head"]] }
> 
> DAVAR中'labels'本身是str类型，怎么通过class_config进行转码呢，这工程中我找了很久没有找到配置class_config的配置文件或者配置。

你这个datalist应该是之前版本的，在最新的datalist中我们已经将其转码成int了，你可以下载最新的datalist。或者可以自己写一个脚本把所有出现的"t-head"转为0，“t-body”转为1, "t-empty"转为2。

**Comment by aaferrero** [comment]
一共就这"t-head"，“t-body”, "t-empty"，三种labels么

**Comment by qiaoliang6** [comment]
> 一共就这"t-head"，“t-body”, "t-empty"，三种labels么

是的

**Comment by aaferrero** [comment]
/demo/table_recognition/lgpma/tools)/convert_html_ann.py但这个文件中并没有如何转成’t-empty‘的转置方法，只有对"t-head"，“t-body”这两个label的转置，这样转换出来的只有两类label，会不会有问题

**Comment by qiaoliang6** [comment]
> /demo/table_recognition/lgpma/tools)/convert_html_ann.py但这个文件中并没有如何转成’t-empty‘的转置方法，只有对"t-head"，“t-body”这两个label的转置，这样转换出来的只有两类label，会不会有问题

抱歉，这个脚本之前更新datalist的时候忘记更新了，现在脚本中不会出现str类型，统一都是用数字类型了。

**Comment by aaferrero** [comment]
第一个我是说你之前说有"t-head"，“t-body”, "t-empty"，三种label，但这个convert_html_ann.py转换脚本转换出来的只有"t-head"，“t-body”这两种类别，也就是说换成数字类型，也就只有类别0和类别1两种类别，没有"t-empty"这个类别2,这样的话和这算法设计的本意是一致的么
第二个最新的转换脚本convert_html_ann.py他，main分支中转换脚本应该也还没改成数字的，
for i in range(1, 1 + span_matrix.max()):
        where = np.where(span_matrix == i)
        s_r, e_r = int(where[0].min()), int(where[0].max())
        s_c, e_c = int(where[1].min()), int(where[1].max())
        cells.append([s_r, s_c, e_r, e_c])
        labels.append(["t-head"]) if i <= num_h else labels.append(["t-body"])
        # labels.append([0]) if i <= num_h else labels.append([1])

    # get bboxes, texts and texts_tokens
    charsign = ['<b>', '<i>', '<sup>', '<sub>', '<underline>', '</b>', '</i>', '</sup>', '</sub>', '</underline>']
    for cell in html['cells']:

代码中把转数字类型的一行注释了，换成转成str类别的，现在我重新注释回来，再试下运行，但不知道这样转成0和1类别和你一开始说0，1，2类别是不是一致。

**Comment by qiaoliang6** [comment]
> 第一个我是说你之前说有"t-head"，“t-body”, "t-empty"，三种label，但这个convert_html_ann.py转换脚本转换出来的只有"t-head"，“t-body”这两种类别，也就是说换成数字类型，也就只有类别0和类别1两种类别，没有"t-empty"这个类别2,这样的话和这算法设计的本意是一致的么 第二个最新的转换脚本convert_html_ann.py他，main分支中转换脚本应该也还没改成数字的， for i in range(1, 1 + span_matrix.max()): where = np.where(span_matrix == i) s_r, e_r = int(where[0].min()), int(where[0].max()) s_c, e_c = int(where[1].min()), int(where[1].max()) cells.append([s_r, s_c, e_r, e_c]) labels.append(["t-head"]) if i <= num_h else labels.append(["t-body"]) # labels.append([0]) if i <= num_h else labels.append([1])
> 
> ```
> # get bboxes, texts and texts_tokens
> charsign = ['<b>', '<i>', '<sup>', '<sub>', '<underline>', '</b>', '</i>', '</sup>', '</sub>', '</underline>']
> for cell in html['cells']:
> ```
> 
> 代码中把转数字类型的一行注释了，换成转成str类别的，现在我重新注释回来，再试下运行，但不知道这样转成0和1类别和你一开始说0，1，2类别是不是一致。

模型训练的是一个mask-rcnn的检测模型，训练的时候只用到2个类别。原来classes_config设计["t-empty"]这个类别只是辅助后处理可视化和其他任务的，所以即便是原来存在3个类别，但是生成的datalist里面都不会出现t-empty类别,所以模型是一致的。
