### ISSUE TITLE
Generating Structures of new table images

### ISSUE THREAD

**Issue by Kehindeajayi01** [hikopensource/DAVAR-Lab-OCR#60]
Hello,
Please how can I use your model to generate the structures of the Modern ICDAR 2019 TRACKB2 Images? Can you point me to a script that generate such?

Thanks

**Comment by qiaoliang6** [comment]
You can inference the model on these images just like inferring the model on PubTabNet (replace the path of datalist).

**Comment by Kehindeajayi01** [comment]
> You can inference the model on these images just like inferring the model on PubTabNet (replace the path of datalist).

Hi **qiaoliang6**, 
Thanks for your prompt response. To infer on PubTabNet, we need to run test_pub.py which needs "config_file = '/path/to/config' # config path" and in the "config" file, we have path to the train, val, and test, and finally the work_dir. So, can you please explain where to replace the path of datalist. Also, ICDAR 2019 test data are just images. Or am I missing the correct script to run?

Thanks
