### ISSUE TITLE
算法结构理解

### ISSUE THREAD

**Issue by Mark-Laohu** [hikopensource/DAVAR-Lab-OCR#61]
您好，我想问下论文中讲到的IMA在代码实现中是不是没用到啊，有IMA文件，但是好像config文件中并没有用到

**Comment by qiaoliang6** [comment]
你好，在原来是的设计中，IMA模块是为了让CMA模块更容易学习。在后续的实验中，我们发现使用预训练模型的基础上，CMA模块可以不需要IMA模块便能收敛的不错。因此，在最终放出来的复现版本中，我们去除了CMA模块，实验性能与之前的模型性能接近（训练充分的情况下），但是会更加节省内存一点。如果需要使用，仍然可以将IMA模块当成一个辅助分支加入到网络模型当中。

**Comment by Mark-Laohu** [comment]
好的谢谢回答！
