### ISSUE TITLE
VSR测试时可视化报错

### ISSUE THREAD

**Issue by YuShinHye** [hikopensource/DAVAR-Lab-OCR#63]
修改tools/test.py文件230行：
`outputs = single_gpu_test(model, data_loader, True, args.show_dir, args.show_score_thr, model_type)`
执行demo/text_layout/VSR/DocBank/test.sh报错：
`File "/home/miniconda3/envs/vsr/lib/python3.7/site-packages/mmdet/core/visualization/image.py", line 76, in imshow_det_bboxes
    'bboxes.shape[0] and labels.shape[0] should have the same length.'
AssertionError: bboxes.shape[0] and labels.shape[0] should have the same length.`
请问是哪里的问题？

执行demo/text_layout/VSR/PubLayNet/test.sh之后可视化结果和终端输出结果不太一样，可视化里面的title有很多：
![图片](https://user-images.githubusercontent.com/92203078/156869983-70033ba3-eb5d-46af-9d62-c5a185b98a38.png)
![图片](https://user-images.githubusercontent.com/92203078/156870037-f1c42d21-5a15-49cc-b178-08df4d58691f.png)
![图片](https://user-images.githubusercontent.com/92203078/156870056-fcf89efd-fa45-4286-bf3a-95014c797031.png)

**Comment by hik-zhangpeng** [comment]
We add the visualization code and remove the bug.
Code will be released in the end of this month.

**Comment by qiaoliang6** [comment]
The code has been updated in [e14ed62](https://github.com/hikopensource/DAVAR-Lab-OCR/commit/e14ed6268f39e2efd7afd6fd4e94f3a1a0f52cf0)
