### ISSUE TITLE
What dose RF visual and RF total mean?

### ISSUE THREAD

**Issue by Gaoxj2020** [hikopensource/DAVAR-Lab-OCR#65]

**Comment by qiaoliang6** [comment]
RF-Learning  has two training stages. 
In the 1st stage, the model is only trained for the visual character counting task. We name it RF-visual.
In the 2nd stage, the model is trained with both of visual character counting and scene text recognition tasks to a achieve the recropocal fearture learning, which is named as RF-total. 
More details can be found in the paper.

**Comment by Gaoxj2020** [comment]
> ned for the visual character counting task. We name it RF-visual.
> In the 2nd stage, the m

Thanks for your reply! And in the counting branch, I note you first output the occurrence numbers at each possible character, then apply a mse loss to calculate the losses between the summary of the occurrence numbers and target length. I wonder have you tried to directly output the text length (0~max_seq_len) to calculate loss, what kind of effect does it bring?

**Comment by qiaoliang6** [comment]
> > ned for the visual character counting task. We name it RF-visual.
> > In the 2nd stage, the m
> 
> Thanks for your reply! And in the counting branch, I note you first output the occurrence numbers at each possible character, then apply a mse loss to calculate the losses between the summary of the occurrence numbers and target length. I wonder have you tried to directly output the text length (0~max_seq_len) to calculate loss, what kind of effect does it bring?

Yes, we have tried the implementation method as you mentioned. However, the performance is not satisfied. We think the reason is that our current implementation could excavate more detailed supervision.
