### ISSUE TITLE
您好，请问如何将publaynet的数据转化为VSR所需要的形式

### ISSUE THREAD

**Issue by yangheng95** [hikopensource/DAVAR-Lab-OCR#69]
您好！谢谢你的工作！我在demo/text_layout 中看到了参考Docbank的例子描述，但是未能找到。请问您能指路一下脚本的地址吗，十分谢谢！

**Comment by qiaoliang6** [comment]
demo/text_layout/datalist/readme.md

**Comment by yangheng95** [comment]
感谢您的回复！我注意到Pbulaynet的config文件中的num_classes=6，但实际只有5类。请问如何在VSR自定义数据集中对应labels和num_classese。
另外，请问您label与其index在test.sh脚本中错位可能是什么问题。多谢指教，谢谢！

**Comment by hik-zhangpeng** [comment]
1、num_classes=6而实际只有5类。PubLayNet数据集中对于文档头部的有些文本没有标注，而PDF解析工具可以将其解析出来，故我们将其定义为label=0，其他类别依次顺延，故num_classes=6.
![num_classes6](https://user-images.githubusercontent.com/97432563/163337350-f45f4e5c-c8bc-458a-96b8-b4e0bbdd5ab1.png)

2、“另外，请问您label与其index在test.sh脚本中错位可能是什么问题。多谢指教，谢谢！”这个没太明白，方便附图说明么？
