### ISSUE TITLE
Questions about the implementations of RF-Learning

### ISSUE THREAD

**Issue by Pay20Y** [hikopensource/DAVAR-Lab-OCR#7]
Hi, thanks for your work. I wonder what "RF-Learning **visual**" means, and why the output dimension of the final FC layer in [counting_head](https://github.com/hikopensource/DAVAR-Lab-OCR/blob/ee248f3ad8718e43a119f41d538bea28c5e7e269/davarocr/davarocr/davar_rcg/models/sequence_heads/counting_head.py#L61) is the number of the character classes (since the prediction target is the text length)?

**Comment by qiaoliang6** [comment]
The "Visual stage" here means the visual character counting, and we have changed it into a clearer expression. For the second question, the supervision of text length is transformed into the occurrence number of characters (whose sum is the text length). It can achieve better performance than direct text length prediction in our experiments. This is mentioned in section 3.3 of the paper.

**Comment by Pay20Y** [comment]
> The "Visual stage" here means the visual character counting, and we have changed it into a clearer expression. For the second question, the supervision of text length is transformed into the occurrence number of characters (whose sum is the text length). It can achieve better performance than direct text length prediction in our experiments. This is mentioned in section 3.3 of the paper.

Thanks for your reply. The counting process is different from ACE on the way of predicting, i.e. ACE adopts a pixel-level prediction and an additional aggregating process, and this paper predicts the number of characters in a global-level, is that right?

**Comment by qiaoliang6** [comment]
> > The "Visual stage" here means the visual character counting, and we have changed it into a clearer expression. For the second question, the supervision of text length is transformed into the occurrence number of characters (whose sum is the text length). It can achieve better performance than direct text length prediction in our experiments. This is mentioned in section 3.3 of the paper.
> 
> Thanks for your reply. The counting process is different from ACE on the way of predicting, i.e. ACE adopts a pixel-level prediction and an additional aggregating process, and this paper predicts the number of characters in a global-level, is that right?

Yes, the character counting branch only focuses on the number of characters in the image. The task is more intuitive. It does not need to pay attention to the relevant information of character categories, and obtains the corresponding features of characters from a global perspective.

**Comment by Pay20Y** [comment]
> > > The "Visual stage" here means the visual character counting, and we have changed it into a clearer expression. For the second question, the supervision of text length is transformed into the occurrence number of characters (whose sum is the text length). It can achieve better performance than direct text length prediction in our experiments. This is mentioned in section 3.3 of the paper.
> > 
> > 
> > Thanks for your reply. The counting process is different from ACE on the way of predicting, i.e. ACE adopts a pixel-level prediction and an additional aggregating process, and this paper predicts the number of characters in a global-level, is that right?
> 
> Yes, the character counting branch only focuses on the number of characters in the image. The task is more intuitive. It does not need to pay attention to the relevant information of character categories, and obtains the corresponding features of characters from a global perspective.

Really appreciate your answers, I will close this issue.
