### ISSUE TITLE
您好，表格识别的这种情况需要怎么处理？

### ISSUE THREAD

**Issue by cumthxy** [hikopensource/DAVAR-Lab-OCR#70]
例如这个表格的识别：
<img width="563" alt="image" src="https://user-images.githubusercontent.com/22782047/160995371-34ae8ea5-4197-40ea-85cf-6ab1587ed941.png">

这种识别结果，有的是一行的数据却成为了2个框。或者框的位置不准确。后期ocr识别结果 做iou计算的话，也会影响到后期的html的结构。
请问这种情况后续该怎么处理？是需要重新再训练一个适合这样表结构的模型么

**Comment by qiaoliang6** [comment]
放出来的模型只在PubTabNet上训练过，想在其他表格上适用只能重新训一个。最好是训一个表格模型，一个单纯的OCR模型，然后使用逻辑去拼接了，比如将所有文字的框和单元格的框去做匹配，和同一个单元格匹配上的文字框拼接一下出最终结果。

**Comment by qiaoliang6** [comment]
联合OCR结果的示例已更新，请参考[03a4c9c](https://github.com/hikopensource/DAVAR-Lab-OCR/commit/03a4c9c4862b0db2519bac877c12548733c365a2)
