### ISSUE TITLE
关于pyramid mask 

### ISSUE THREAD

**Issue by ai1361720220000** [hikopensource/DAVAR-Lab-OCR#78]
按论文的意思应该文本中心的响应值为1，但是按公式来看，好像并不是。以horizontal为例，公式不应该是在w=x1的地方响应值为1吗？，文本中心的响应是(x1+x2)/2*x1。

**Comment by qiaoliang6** [comment]
非常感谢您的指正！这个是因为论文中那个公式书写上有点问题，代码实现和论文本身想表达的意思是一致的，就是文本中心的响应是1。这个公式更新后如下图所示。
<img width="462" alt="Snipaste_2022-04-20_11-11-24" src="https://user-images.githubusercontent.com/86286845/164144329-a700dad2-c302-4724-b7aa-167cc3068787.png">
Arxiv上面的论文我们会稍后更正一下。

**Comment by ai1361720220000** [comment]
> 非常感谢您的指正！这个是因为论文中那个公式书写上有点问题，代码实现和论文本身想表达的意思是一致的，就是文本中心的响应是1。这个公式更新后如下图所示。 <img alt="Snipaste_2022-04-20_11-11-24" width="462" src="https://user-images.githubusercontent.com/86286845/164144329-a700dad2-c302-4724-b7aa-167cc3068787.png"> Arxiv上面的论文我们会稍后更正一下。

这样就对上啦，另外请问下在lgpma_base.py中的resnet50-19c8e357.pth，需要在哪里下载呢？

**Comment by ai1361720220000** [comment]
> 非常感谢您的指正！这个是因为论文中那个公式书写上有点问题，代码实现和论文本身想表达的意思是一致的，就是文本中心的响应是1。这个公式更新后如下图所示。 <img alt="Snipaste_2022-04-20_11-11-24" width="462" src="https://user-images.githubusercontent.com/86286845/164144329-a700dad2-c302-4724-b7aa-167cc3068787.png"> Arxiv上面的论文我们会稍后更正一下。

还有一个问题，batchsize和配置一样，为什么我训练的时候看一个epoch需要迭代79815轮，但是从你提供的pub_train.log看只需要19955。
我训练log打印：
![image](https://user-images.githubusercontent.com/24642194/164593394-6556b35b-c86e-43c3-9799-f3d6014cc0e2.png)

你提供的log：
![image](https://user-images.githubusercontent.com/24642194/164593430-75036a34-b9bd-42eb-ad65-14db21ceb95e.png)

**Comment by ZaishengLi** [comment]
> > 非常感谢您的指正！这个是因为论文中那个公式书写上有点问题，代码实现和论文本身想表达的意思是一致的，就是文本中心的响应是1。这个公式更新后如下图所示。 <img alt="Snipaste_2022-04-20_11-11-24" width="462" src="https://user-images.githubusercontent.com/86286845/164144329-a700dad2-c302-4724-b7aa-167cc3068787.png"> Arxiv上面的论文我们会稍后更正一下。
> 
> 还有一个问题，batchsize和配置一样，为什么我训练的时候看一个epoch需要迭代79815轮，但是从你提供的pub_train.log看只需要19955。 我训练log打印： ![image](https://user-images.githubusercontent.com/24642194/164593394-6556b35b-c86e-43c3-9799-f3d6014cc0e2.png)
> 
> 你提供的log： ![image](https://user-images.githubusercontent.com/24642194/164593430-75036a34-b9bd-42eb-ad65-14db21ceb95e.png)

这个训练框架里的batchsize指的是每张GPU的batchsize，所以迭代轮数和batchsize以及GPU数量都有关。我猜想你是2卡训练的，之前的log文件是8卡训练的，正好是4倍关系。
