### ISSUE TITLE
vis for table recognition

### ISSUE THREAD

**Issue by cloudfool** [hikopensource/DAVAR-Lab-OCR#8]
Hi,
Could you pls tell me how  to generate the vis images like below, tks!
![PMC2871264_002_00](https://user-images.githubusercontent.com/22359737/134350323-57a40191-9f46-4317-84be-073df36e8a41.png)

**Comment by qiaoliang6** [comment]
In the postprocess of LGPMA, you can return both of the 'html_list' and the 'bboxes' items, and then draw those 'bboxes' on the original images in the test script. We will update the script later.
