### ISSUE TITLE
lgpma表格识别模型预测的结果

### ISSUE THREAD

**Issue by tangxxiii** [hikopensource/DAVAR-Lab-OCR#82]
您好，我在用lpgma模型预测表格结构时，发现result['bboxes']不是按照html中单元格位置顺序排列的。如果我获得了表格文本，想放进html中生成完整表格，那应该怎么处理result['bbox']使得其顺序和result['html']的格式一样？

**Comment by qiaoliang6** [comment]
我们稍后会放出在PubTabNet上面增加OCR的模型结果，届时可以参考一下

**Comment by qiaoliang6** [comment]
联合OCR结果的示例已更新，请参考[03a4c9c](https://github.com/hikopensource/DAVAR-Lab-OCR/commit/03a4c9c4862b0db2519bac877c12548733c365a2)

**Comment by tangxxiii** [comment]
> 联合OCR结果的示例已更新，请参考[03a4c9c](https://github.com/hikopensource/DAVAR-Lab-OCR/commit/03a4c9c4862b0db2519bac877c12548733c365a2)

非常感谢！
