### ISSUE TITLE
关于LGPMA在SciTSR数据集上的指标

### ISSUE THREAD

**Issue by BangdongChen** [hikopensource/DAVAR-Lab-OCR#83]
请问LGPMA在SciTSR上计算P,R,F指标的时候，采用的IoU阈值是多少呢？能否提供一下评测脚本？

**Comment by qiaoliang6** [comment]
SciTSR官方github有提供测试脚本，我们是使用原始脚本测试测试的结果

**Comment by BangdongChen** [comment]
> SciTSR官方github有提供测试脚本，我们是使用原始脚本测试测试的结果

okk是我理解错了。该测试脚本是需要单元格的text content的，不同论文在获得text content的ocr识别器并不一致，这样是否存在对比不公平的问题？

**Comment by qiaoliang6** [comment]
> > SciTSR官方github有提供测试脚本，我们是使用原始脚本测试测试的结果
> 
> okk是我理解错了。该测试脚本是需要单元格的text content的，不同论文在获得text content的ocr识别器并不一致，这样是否存在对比不公平的问题？

这个问题确实不可避免，所以在最新的PubTabNet中也提供了只评价结构的选项。但是完整表格识别的任务的评估确实需要考虑到OCR的性能。在SciTSR上的一般做法有2种，如果是直接用ocr引擎推理，会用gt去和预测做个最大匹配；或者也可以单独训个单行的文本检测和识别模型（都是印刷体准确率也都比较高）。

**Comment by BangdongChen** [comment]
> > > SciTSR官方github有提供测试脚本，我们是使用原始脚本测试测试的结果
> > 
> > 
> > okk是我理解错了。该测试脚本是需要单元格的text content的，不同论文在获得text content的ocr识别器并不一致，这样是否存在对比不公平的问题？
> 
> 这个问题确实不可避免，所以在最新的PubTabNet中也提供了只评价结构的选项。但是完整表格识别的任务的评估确实需要考虑到OCR的性能。在SciTSR上的一般做法有2种，如果是直接用ocr引擎推理，会用gt去和预测做个最大匹配；或者也可以单独训个单行的文本检测和识别模型（都是印刷体准确率也都比较高）。

非常感谢您的解答！
