### ISSUE TITLE
您好，请问FREE什么时候会开源？

### ISSUE THREAD

**Issue by imMid-Star** [hikopensource/DAVAR-Lab-OCR#85]
您好，请问FREE什么时候会开源？

**Comment by qiaoliang6** [comment]
> 您好，请问FREE什么时候会开源？

非常抱歉，由于原版算法是在caffe上实现的，迁移至当前框架有一定的工作量，原先负责该算法的同事已经转岗，目前团队内因为有其他优先级更高的任务，因此该算法的迁移计划可能要等团队内部有相关开发需求时才能开展。不过之前仓库里面之前已经开源的YORO算法，FREE相当于是其的扩展（将文字检测识别用端到端网络实现），两者的基本思想是一致的。
