### ISSUE TITLE
LGPMA inference bug KeyError: 'bboxes'

### ISSUE THREAD

**Issue by Kins1ley** [hikopensource/DAVAR-Lab-OCR#88]
对单张图片inference的结果如下
![image](https://user-images.githubusercontent.com/26199647/171604297-47cd282f-14fd-4f22-afb9-82378916742f.png)

结果里面没有包括bboxes，在可视化阶段就会报错
![image](https://user-images.githubusercontent.com/26199647/171604068-555e5bf5-aaca-4139-b682-90f8cd4c70d9.png)

**Comment by qiaoliang6** [comment]
这张图片可以通过邮件发送一下，看看能否定位问题？

**Comment by GordonImimr** [comment]
Hello, I also have this issue. Should I email you guys too?

**Comment by qiaoliang6** [comment]
This problem is fixed in 88988bd804b658ae628eff292e17c7620f15590f
