### ISSUE TITLE
No module named 'mmcv.runner.dist_utils'

### ISSUE THREAD

**Issue by surelyee** [hikopensource/DAVAR-Lab-OCR#9]
Hello~ when to upload dist_utils files?

**Comment by qiaoliang6** [comment]
'mmcv' and 'mmdet' are third_party modules that can be installed using PIP tool. You can also install it following the official instruction on:  https://github.com/open-mmlab/mmcv.

**Comment by surelyee** [comment]
> 'mmcv' and 'mmdet' are third_party modules that can be installed using PIP tool. You can also install it following the official instruction on: https://github.com/open-mmlab/mmcv.
thanks~
